# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/chris/workspace/sp22-e520-lab-assignment7-ychen0223/part1/IP_Integrator/support/uart_led.xdc

# Block Designs: bd/UART_LED_Subsystem/UART_LED_Subsystem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_LED_Subsystem || ORIG_REF_NAME==UART_LED_Subsystem} -quiet] -quiet

# IP: bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_led_ctl_0_0/UART_LED_Subsystem_led_ctl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_LED_Subsystem_led_ctl_0_0 || ORIG_REF_NAME==UART_LED_Subsystem_led_ctl_0_0} -quiet] -quiet

# IP: bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_meta_harden_1_0/UART_LED_Subsystem_meta_harden_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_LED_Subsystem_meta_harden_1_0 || ORIG_REF_NAME==UART_LED_Subsystem_meta_harden_1_0} -quiet] -quiet

# IP: bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_meta_harden_2_0/UART_LED_Subsystem_meta_harden_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_LED_Subsystem_meta_harden_2_0 || ORIG_REF_NAME==UART_LED_Subsystem_meta_harden_2_0} -quiet] -quiet

# IP: bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_util_ds_buf_0_0/UART_LED_Subsystem_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_LED_Subsystem_util_ds_buf_0_0 || ORIG_REF_NAME==UART_LED_Subsystem_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_uart_baud_gen_0_0/UART_LED_Subsystem_uart_baud_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_LED_Subsystem_uart_baud_gen_0_0 || ORIG_REF_NAME==UART_LED_Subsystem_uart_baud_gen_0_0} -quiet] -quiet

# IP: bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_meta_harden_0_0/UART_LED_Subsystem_meta_harden_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_LED_Subsystem_meta_harden_0_0 || ORIG_REF_NAME==UART_LED_Subsystem_meta_harden_0_0} -quiet] -quiet

# IP: bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_uart_rx_ctl_0_0/UART_LED_Subsystem_uart_rx_ctl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_LED_Subsystem_uart_rx_ctl_0_0 || ORIG_REF_NAME==UART_LED_Subsystem_uart_rx_ctl_0_0} -quiet] -quiet

# IP: bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_xlconstant_0_1/UART_LED_Subsystem_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_LED_Subsystem_xlconstant_0_1 || ORIG_REF_NAME==UART_LED_Subsystem_xlconstant_0_1} -quiet] -quiet

# XDC: /home/chris/workspace/sp22-e520-lab-assignment7-ychen0223/part1/UART_LED_Subsystem.gen/sources_1/bd/UART_LED_Subsystem/UART_LED_Subsystem_ooc.xdc
