# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chris/workspace/sp22-e520-lab-assignment7-ychen0223/part1/UART_LED_Subsystem.srcs/sources_1/bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_util_ds_buf_0_0/UART_LED_Subsystem_util_ds_buf_0_0.xci
# IP: The module: 'UART_LED_Subsystem_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chris/workspace/sp22-e520-lab-assignment7-ychen0223/part1/UART_LED_Subsystem.gen/sources_1/bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_util_ds_buf_0_0/UART_LED_Subsystem_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_LED_Subsystem_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/chris/workspace/sp22-e520-lab-assignment7-ychen0223/part1/UART_LED_Subsystem.gen/sources_1/bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_util_ds_buf_0_0/UART_LED_Subsystem_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_LED_Subsystem_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/chris/workspace/sp22-e520-lab-assignment7-ychen0223/part1/UART_LED_Subsystem.srcs/sources_1/bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_util_ds_buf_0_0/UART_LED_Subsystem_util_ds_buf_0_0.xci
# IP: The module: 'UART_LED_Subsystem_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chris/workspace/sp22-e520-lab-assignment7-ychen0223/part1/UART_LED_Subsystem.gen/sources_1/bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_util_ds_buf_0_0/UART_LED_Subsystem_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_LED_Subsystem_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/chris/workspace/sp22-e520-lab-assignment7-ychen0223/part1/UART_LED_Subsystem.gen/sources_1/bd/UART_LED_Subsystem/ip/UART_LED_Subsystem_util_ds_buf_0_0/UART_LED_Subsystem_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_LED_Subsystem_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
